language: cpp
env:
  - CXX=g++-4.8 CC=gcc-4.8
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo add-apt-repository ppa:h-rayflood/llvm -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libsdl2 libsdl2-dev g++-4.8 -y
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  make && ./runUnitTests
  