language: cpp
env:
  - CXX=g++-4.8 CC=gcc-4.8
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo add-apt-repository ppa:h-rayflood/llvm -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libsdl2 libsdl2-dev g++-4.8 -y
  - wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
  - tar -xf SDL2_image-2.0.0.tar.gz
  - cd SDL2_image-2.0.0
  - ./configure && make && sudo make install
  - cd -
before_script:
  - mkdir build
  - cd build
  - CXX=g++-4.8 CC=gcc-4.8 cmake ..
script:
  make && ./runUnitTests
  