language: cpp
compiler:
  - clang
before_install:
  - sudo add-apt-repository ppa:josebagar/sdl2
  - sudo apt-get install libsdl2
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  make && ./runUnitTests
  